twitch-rs/twitch_api

Cargo.lock, oauth2/Cargo.toml, oauth2/README.md, oauth2/src/lib.rs, release.toml, twitchapi/Cargo.toml, twitchapi/README.md, twitchapi/src/lib.rs
- add `ChannelEditCommercial` scope.
- fix status code in, kinda...
- rename `helix::channel` to `helix::channels`, and rename `GetChannel` to `GetChannelInformation`
- `RequestError::QuerySerializeError` is a custom serializers error now.
- added `start_commercial`, `check_automod_status` and `get_broadcaster_subscriptions`
- removed dependency on `serde_urlencoded`
=> release twitch_oauth2 0.4.1 & release twitch_api2 0.4.0 

.gitignore, src/client.rs
rustc would for example say
```
expected a `std::ops::Fn<(http::request::Request<std::vec::Vec<u8>>,)>` closure, found `reqwest::Client`
...
= help: the trait `std::ops::Fn<(http::request::Request<std::vec::Vec<u8>>,)>` is not implemented for `reqwest::Client`
= note: required because of the requirements on the impl of `twitch_api2::HttpClient<'static>` for `reqwest::Client`
```
which is very hard to understand
=> Disable trait impl that makes errors confusing

Cargo.toml, examples/get_hosts.rs, src/tmi/mod.rs
Added support for the `get_hosts` endpoint of TMI, which can either get a list of hosts hosting a target channel, *or* get the channel that is being hosted by a given channel. Also added an example, which requires a host channel ID, then checks if any other channels are hosting the target. We could get the channel ID given a username using Helix, but that would then require an auth token.
=> Add `get_hosts` endpoint to TMI

README.md, examples/automod_check.rs, examples/channel_information.rs, examples/client.rs, examples/create_follower.rs, examples/get_channel_status.rs, examples/get_moderation.rs, examples/get_streams_and_chatters.rs, examples/modify_channel.rs, src/helix/bits.rs, src/helix/channels.rs, src/helix/clips.rs, src/helix/games.rs, src/helix/mod.rs, src/helix/moderation.rs, src/helix/search.rs, src/helix/streams.rs, src/helix/subscriptions.rs, src/helix/tags.rs, src/helix/users.rs, src/helix/videos.rs
Counterpart to https://github.com/Emilgardis/twitch_oauth2/pull/22
=> Update to user token constructor change

src/pubsub/channel_points.rs, src/pubsub/mod.rs
Two bug fixes:
1 - We're missing PONG and RECONNECT responses from the server, so they're coming in as errors.
2 - Reward `cooldown_expires_at` is a timestamp, not amount of seconds, so that's erroring when parsing
=> PubSub bug fixes

CHANGELOG.md, src/helix/mod.rs, src/helix/streams.rs, src/helix/streams/replace_stream_tags.rs
I added `PUT Replace Stream Tags`
The `RequestPut` needs to have a Body Parameter for that.
This is currently incompatible with `PUT Block User`, Should `PUT Block User` get an empty Body, or should `RequestPut` have two implementations (Bodyless and with Body)
=> [WIP] Added Replace Stream Tags to helix.

src/helix/search/search_categories.rs, src/helix/search/search_channels.rs
Search Categories returns a null value when the search is empty
Also corrects wrong path in Search Channels
fixes #92
=> make Search endpoints not error on empty search result and fix Search Channels

src/helix/users/get_users_follows.rs, src/helix/webhooks/topics/users/user_follows.rs
Adds missing field `to_login` in struct `UsersFollow`
I've added it as a required parameter since it seemed to be so but I'm not sure that is the case
=> Added missing field in UsersFollow

README.md, src/eventsub/mod.rs, src/helix/eventsub/create_eventsub_subscription.rs, src/helix/eventsub/get_eventsub_subscriptions.rs
bors r+
- bump twitch_oauth2
- deprecated eventsub limit
- remove unnecessary client_id
=> more changes

CHANGELOG.md, src/helix/bits/get_bits_leaderboard.rs, src/helix/channels/get_channel_information.rs, src/helix/channels/modify_channel_information.rs, src/helix/eventsub/create_eventsub_subscription.rs, src/helix/eventsub/get_eventsub_subscriptions.rs, src/helix/mod.rs, src/helix/points.rs, src/helix/points/create_custom_rewards.rs, src/helix/points/update_custom_reward.rs, src/helix/points/update_redemption_status.rs, src/helix/search/search_categories.rs, src/helix/subscriptions/check_user_subscription.rs, src/helix/users/get_users_follows.rs, src/helix/webhooks/get_webhook_subscriptions.rs
I'm not sure this is the right way to do this. I'm not a particularly experienced rustacean, so please let me know if this has issues I can't see.
It does, however, _work_ - I have a (private) project that is now successfully using it, and I can update rewards successfully.
The most likely issue is that the endpoint here returns the updated CustomReward structure, and we're just losing it here. That shouldn't be a big deal - if you're patching it you should know what it will look like after a successful response - but it is betraying the twitch API slightly. However I couldn't figure out how to fit that into the existing structures around the client :(
=> Implementing UpdateCustomReward

src/helix/search/search_channels.rs
The field "tags_ids" is supposed to be "tag_ids" :)
=> Fix typo in helix::search::Channel

CHANGELOG.md, src/helix/channels/modify_channel_information.rs, src/helix/client_ext.rs, src/helix/eventsub/delete_eventsub_subscription.rs, src/helix/mod.rs, src/helix/points/delete_custom_reward.rs, src/helix/points/update_redemption_status.rs, src/helix/streams/replace_stream_tags.rs, src/helix/users/block_user.rs, src/helix/users/create_user_follows.rs, src/helix/users/delete_user_follows.rs, src/helix/users/unblock_user.rs, src/helix/videos/delete_videos.rs
- refactor Delete and Put
- remove specific error enum variants since they are never hit
- improve error messages
this changes a lot, in particular, removes some variants because of parse_response catching almost all of it. So far, I have not observed an error catched by `*::InvalidResponse` (except when twitch returns 200 instead of 204).
fixes #126
=> better delete put

src/helix/points/delete_custom_reward.rs
As with the helix-eventsub delete request, Twitch seems to return 200 OK. I haven't tested the other `DELETE` endpoints but I'd expect similar results.
=> fix(helix/points): accept OK as valid DELETE status code

src/types.rs
Small fix: the correct broadcaster type name is "affiliate", not "affiliated".
=> Fix broadcaster type affiliate name

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/get_streams_and_chatters.rs, src/eventsub/mod.rs, src/helix/client_ext.rs, src/helix/eventsub/create_eventsub_subscription.rs, src/pubsub/hypetrain.rs, src/tmi/mod.rs
* Added Helix endpoints:
*  `Manage Held AutoMod Messages`
*  `Get Global Chat Badges`
*  `Get Channel Chat Badges`
*  `Get Channel Emotes`
*  `Get Global Emotes`
*  `Get Emote Sets`
*  `Get Channel Stream Schedule`
*  `Update Channel Stream Schedule`
*  `Create Channel Stream Schedule Segment`
*  `Delete Channel Stream Schedule Segment`
* Added Channel Terms to pubsub `chat_moderator_actions`
* Added `user-moderation-notifications` topic to pubsub
* Added `extendsub` to pubsub `channel-subscribe-events-v1`
* Added `delay` to `Get Channel Information`
* Added `serde::Serialize` to all helix endpoint return values
* Added `channel.subscription.end` to EventSub
* Added `channel.subscription.gift` to EventSub
* Added `channel.subscription.message` to EventSub
* Added …
=> release version 0.6.0-rc.1

src/eventsub/channel/channel_points_custom_reward_redemption/add.rs, src/eventsub/channel/channel_points_custom_reward_redemption/update.rs
Small fix: redemption id has the wrong type in eventsub payloads.
=> Fix redemption incorrect id type

CHANGELOG.md, src/pubsub/mod.rs
This PR adds (or rather enables) the unlisten command for pubsub and tests.
This is a WIP because I'm not really sure if the `auth_token` should be included in the command as the docs are really vague about it.
* Chatterino _doesn't_ include the `auth_token` ([permalink](https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/PubsubHelpers.cpp#L82-L104)).
* `go-twitch-pubsub` _doesn't_ include the `auth_token` ([permalink](https://github.com/tracy-and-matt/go-twitch-pubsub/blob/2db33baf9ef0ed7373e2712912102f4775a80fbd/pubsub.go#L342-L353))
* Twitch4j _does_ include the `auth_token` (if I understand the code correctly):
1. [Includes the data](https://github.com/twitch4j/twitch4j/blob/f291fb5b0e8f4b2032437c97d09f4aa7e11d8059/pubsub/src/main/java/com/github/twitch4j/pubsub/ …
=> feat(pubsub): enable/add unlisten_command

CHANGELOG.md, src/pubsub/automod_queue.rs, src/pubsub/channel_bits.rs, src/pubsub/channel_bits_badge.rs, src/pubsub/channel_cheer.rs, src/pubsub/channel_points.rs, src/pubsub/channel_sub_gifts.rs, src/pubsub/channel_subscriptions.rs, src/pubsub/community_points.rs, src/pubsub/following.rs, src/pubsub/hypetrain.rs, src/pubsub/mod.rs, src/pubsub/moderation.rs, src/pubsub/raid.rs, src/pubsub/user_moderation_notifications.rs, src/pubsub/video_playback.rs
This PR implements
* `Clone` for the `Topics` enum (all subtopics already implement `Clone`)
* `Hash` for all topics
=> feat(pubsub): implement `Clone` and `Hash` for topics

CHANGELOG.md, src/pubsub/moderation.rs
`moderator_removed` was beleived to not exist, however it exists.
In this case the listening user was removed as a moderator.
Example response:
```json
{
"type": "moderator_removed",
"data": {
"channel_id": "129546453",
"target_user_id": "691109305",
"moderation_action": "unmod",
"target_user_login": "rewardmore",
"created_by_user_id": "129546453",
"created_by": "nerixyz"
}
}
```
Raw:
```json
{"type":"MESSAGE","data":{"topic":"chat_moderator_actions.691109305.129546453","message":"{\"type\":\"moderator_removed\",\"data\":{\"channel_id\":\"129546453\",\"target_user_id\":\"691109305\",\"moderation_action\":\"unmod\",\"target_user_login\":\"rewardmore\",\"created_by_user_id\":\"129546453\",\"created_by\":\"nerixyz\"}}"}}
```
=> feat(pubsub): add `moderator_removed` moderation action

src/client.rs, src/helix/channels/get_channel_information.rs, src/helix/channels/modify_channel_information.rs, src/helix/eventsub/delete_eventsub_subscription.rs, src/helix/points/delete_custom_reward.rs, src/helix/streams/replace_stream_tags.rs
- Status was not carried over when translating responses.
- Wrong type for username/display name in channel information. Also missing broadcaster_login (not documented, yet :) )
carried over from #190 c8307a876ec6d63a3b18ad6c25f676d55ad6d5fe
=> Fix some issues

.vscode/settings.json, CHANGELOG.md, Cargo.lock, Cargo.toml, examples/automod_check.rs, examples/channel_information.rs, examples/client.rs, examples/followed_streams.rs, examples/get_channel_status.rs, examples/get_moderation.rs, examples/mock_api.rs, examples/modify_channel.rs, src/helix/client_ext.rs, src/helix/mod.rs, src/helix/search/search_channels.rs, src/helix/webhooks/topics/mod.rs, src/lib.rs, src/tmi/mod.rs
This aims to bring in twitch-cli to CI and for users. More changes to be done in future prs
Remaining:
=> implement mocking

src/helix/bits/get_bits_leaderboard.rs, src/helix/channels/get_channel_information.rs, src/helix/channels/modify_channel_information.rs, src/helix/eventsub/create_eventsub_subscription.rs, src/helix/eventsub/delete_eventsub_subscription.rs, src/helix/eventsub/get_eventsub_subscriptions.rs, src/helix/mod.rs, src/helix/moderation/manage_held_automod_messages.rs, src/helix/points/create_custom_rewards.rs, src/helix/points/delete_custom_reward.rs, src/helix/points/update_custom_reward.rs, src/helix/points/update_redemption_status.rs, src/helix/polls/create_poll.rs, src/helix/polls/end_poll.rs, src/helix/predictions/create_prediction.rs, src/helix/predictions/end_prediction.rs, src/helix/schedule/update_channel_stream_schedule.rs, src/helix/schedule/update_channel_stream_schedule_segment.rs, src/helix/search/search_categories.rs, src/helix/streams/replace_stream_tags.rs, src/helix/subscriptions/check_user_subscription.rs, src/helix/subscriptions/get_broadcaster_subscriptions.rs, src/helix/users/block_user.rs, src/helix/users/get_users_follows.rs, src/helix/users/unblock_user.rs, src/helix/videos/delete_videos.rs
fixes getting points for broadcaster subscriptions
I'm not sure I like this approach. See for example https://github.com/Emilgardis/twitch_api2/blob/463d5bb915dd0f394c9131687d16eaf12e0f70da/src/helix/bits/get_bits_leaderboard.rs#L125-L159.
Broadcaster subscriptions used to have this, but was changed in #156
=> implement getting other fields in normal responses

README.md
It was sending you to https://docs.rs/twitch_api, and not to https://docs.rs/twitch_api2.
=> Fixing links at README

src/eventsub/event.rs, src/eventsub/mod.rs
To check the `Twitch-Eventsub-Subscription-Type` header, I need to compare it to the `EventType`. When creating a guard for an eventsub route, the `EventType` is already known, so the guard should just compare strings/bytes. However, the only way of getting the string representation is through `impl Display`, which allocates. That's why I'm adding `to_str` (which is marked as const so rustc hopefully computes the output at compile time in generic functions).
When adding `to_str` we might as well add `FromStr`, where I didn't really have an idea about the error type, so it's like an `Option` now.
Since the implementations for `to_str` and `FromStr` require a lot of repeating code, I created a macro that implements the whole type.
The type wasn't marked as `Copy`, so I marked it as `Copy` …
=> feat: provide `to_str` and `FromStr` for EventType

CHANGELOG.md, src/helix/client/client_ext.rs, src/helix/endpoints/chat/get_chat_settings.rs, src/helix/endpoints/chat/mod.rs
Adds the [`Get Chat Settings`](https://dev.twitch.tv/docs/api/reference#get-chat-settings) endpoint to helix.
=> feat: add `Get Chat Settings` endpoint

CHANGELOG.md, src/helix/client/client_ext.rs, src/helix/endpoints/chat/mod.rs
- release twitch_api 0.7.0-rc.2
- place Get Chatters behind unsupported,
=> chatters beta

src/pubsub/moderation.rs
I got some warnings that some PubSub messages couldn't be parsed:
```json
{
"type": "MESSAGE",
"data": {
"topic": "chat_moderator_actions.691109305.120183018",
"message": "{\"type\":\"moderation_action\",\"data\":{\"type\":\"chat_login_moderation\",\"moderation_action\":\"vip\",\"args\":[\"Floikka\"],\"created_by\":\"nam______________________\",\"created_by_user_id\":\"120183018\",\"created_at\":\"2022-12-20T16:41:26.168122804Z\",\"msg_id\":\"\",\"target_user_id\":\"85262774\",\"target_user_login\":\"\",\"from_automod\":false}}"
}
}
```
```json
{
"type": "MESSAGE",
"data": {
"topic": "chat_moderator_actions.691109305.120183018",
"message": "{\"type\":\"moderation_action\",\"data\":{\"type\":\"chat_login_moderation\",\"moderation_action\":\"vip\",\"args\":[\"chubakabraaa\"],\"created_by\":\ …
```
=> fix(pubsub): re-add `Vip` `ModerationActionCommand` Variant

CHANGELOG.md, src/helix/endpoints/teams/get_teams.rs, src/helix/endpoints/teams/mod.rs
This field seems to be nullable (e.g. for team-id `10920`). This PR marks the field as nullable and adds a test response.
Fixes #318.
=> Mark `TeamInformation::thumbnail_url` optional

src/eventsub/event.rs
This was causing compilation errors without the `unsupported` feature.
=> Feature-gate references to feature-gated events

src/helix/endpoints/predictions/create_prediction.rs, src/helix/endpoints/predictions/end_prediction.rs
Creating predictions supports >2 outcomes now: https://dev.twitch.tv/docs/api/reference/#create-prediction
Additionally, cleanup a type error.
(Sorry about the spam, I'm not used to using git on Windows and got something messed up.)
=> Predictions improvements

examples/automod_check.rs, src/helix/endpoints/moderation/check_automod_status.rs
oops, this accidentally regressed when we moved over to references.
Should probably check all the bodies that they return expected data
=> fix automod

Cargo.lock, src/eventsub/event/websocket.rs, src/lib.rs
The `-beta` part was removed from the URL (see [announcement](https://discuss.dev.twitch.tv/t/update-required-for-eventsub-websockets-beta-connection-url/45079) - old URL is valid until 2023-May-15). This updates the constant and one URL in a test-case.
=> Update EventSub WebSocket URL

Cargo.lock, deny.toml
Since the audit currently fails, I'm updating the dependencies here. Most notably, `twitch_oauth2` gets updated to v0.12.9.
=> deps: update all dependencies

src/eventsub/channel/chat/message.rs, src/eventsub/channel/chat/mod.rs, src/eventsub/channel/chat/notification.rs, src/eventsub/channel/mod.rs, src/eventsub/event.rs
After the Helix chat endpoint, this implements the [`channel.chat.message`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatmessage) event for EventSub. I didn't re-export the `Message` types in`twitch_api::eventsub::chat`, since I wasn't sure if that should be done. There are some similarities with [`twitch_api::pubsub::automod_queue::Message`](https://twitch-rs.github.io/twitch_api/twitch_api/pubsub/automod_queue/struct.Message.html), but they aren't compatible.
I left out `deny_unknown_fields` for the `Fragment`, since the JSON always has all optional metadata.
<sub>As a sidenote, with the chat messages being quite large and frequent, maybe it could be nice to support `simd-json` in place of `serde_json` (I think it can be a drop-in replacement).</sub>
=> feat(eventsub): add `channel.chat.message`

src/helix/client.rs, src/helix/client/client_ext.rs
The error type is part of the public api, so it makes sense to expose it as well.
=> export `ClientExtError`

Cargo.lock, Cargo.toml, examples/eventsub/Cargo.toml, examples/eventsub/src/main.rs, examples/eventsub/src/twitch.rs, examples/eventsub_websocket/Cargo.toml, examples/tower_client/Cargo.toml, examples/tower_client/src/main.rs, examples/twitch_oauth2-integration/Cargo.toml, src/client.rs, src/client/reqwest_impl.rs, src/client/surf_impl.rs, src/client/tower_impl.rs, src/client/ureq_impl.rs, src/helix/client.rs, src/helix/client/custom.rs, src/tmi/mod.rs
Additionally, the examples were updated to use dependencies that use http1.
Fixes #401.
=> Update to http 1, reqwest 0.12, and hyper 1

src/eventsub/channel/hypetrain/begin.rs, src/helix/endpoints/moderation/update_shield_mode_status.rs
- `update_shield_mode_status` had a duplicate `//!` and no newline after the heading.
- `ChannelHypeTrainBeginV1Payload` was missing `level` - see https://github.com/orgs/twitch-rs/projects/1/views/3?pane=issue&itemId=14931669
=> Fix `update_shield_mode_status` docs and missing `level` in `ChannelHypeTrainBeginV1Payload`

src/eventsub/mod.rs, src/helix/client/client_ext.rs, src/helix/endpoints/eventsub/create_conduit.rs, src/helix/endpoints/eventsub/get_conduits.rs, src/helix/endpoints/eventsub/mod.rs
This doesn't implement all conduit-related endpoints on purpose since I'm slow/not sure what I'm doing so I thought doing little by little is a better idea
Questions:
1) The token for create_conduit & get_conduits must be an app access token. Can I check that compile-time somehow with a trait or something?
2) I've left a bunch of stuff on the bodies/requests (like typed-builder) that I don't really understand. Please let me know if they should be removed
=> feat: Add Get Conduits & Create Conduit endpoints

src/eventsub/mod.rs, src/helix/client/client_ext.rs, src/helix/endpoints/eventsub/mod.rs, src/helix/endpoints/eventsub/update_conduit_shards.rs
This endpoint is used to update the shards that exist in a previously created conduit.
I have tested this in my own bot, combined with the Create Conduit & Get Conduits endpoint I implemented earlier, and verified that it works as expected (at least for my use case).
I'm not 100% sure if I've covered all edge cases.
I have not updated `eventsub::TransportMethod` because I'm not sure exactly where that's used.
I have not added all helpers to `TransportResponse`/`Transport`, but will do so
=> feat: Add "Update Conduit Shards" endpoint

Cargo.lock
Addressing [RUSTSEC-2024-0336](https://rustsec.org/advisories/RUSTSEC-2024-0336).
=> deps: update `rustls` to v0.21.11

src/helix/client/client_ext.rs, src/helix/endpoints/eventsub/get_conduit_shards.rs, src/helix/endpoints/eventsub/mod.rs
This adds the [Get Conduit Shards](https://dev.twitch.tv/docs/api/reference/#get-conduit-shards) endpoint
I'm open to changing conduit IDs to their own type if that's better for consistency
=> feat: add Get Conduit Shards endpoint

README.md, src/lib.rs, src/pubsub/mod.rs
https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043
=> Deprecate pubsub

CHANGELOG.md, Cargo.lock, src/eventsub/conduit/mod.rs, src/eventsub/conduit/shard/disabled.rs, src/eventsub/conduit/shard/mod.rs, src/eventsub/event.rs, src/eventsub/mod.rs
Adds the [`conduit.shard.disabled`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#conduitsharddisabled) event for EventSub as twitch recommends listening to those when using the conduit transport method.
(First pr for a big rust project like this so I would appreciate any constructive feedback)
=> feat(eventsub): add `conduit.shard.disabled`

src/eventsub/channel/chat/message.rs
Adds the missing types which Twitch has kindly created to mess with us! Should avoid deserialising errors on chat messages. Having a little difficulty testing it locally due to #256 (I think) but happy to try with more guidance: have confirmed the names of the chat message event types via my stream.
=> fix: add new Twitch message types

Cargo.lock, src/helix/client/client_ext.rs, src/helix/endpoints/moderation/mod.rs, src/helix/endpoints/moderation/warn_chat_user.rs
[Twitch Docs](https://dev.twitch.tv/docs/api/reference/#warn-chat-user)
I wasn't sure about the naming since no other endpoint has `chat-user` instead of just `user` but I decided to stick with the same name as Helix. LMK if I should change everything to just `warn-user`. 
I'm also not sure if I should catch 0-length reasons in `try_to_body` or keep the current behavior and let Helix return an error. Other than that, everything seemed to work based on my testing.
=> feat: Add `Warn Chat User` endpoint

Cargo.lock, Cargo.toml, examples/eventsub_websocket/src/websocket.rs, src/eventsub/channel/chat/message.rs, src/eventsub/event/websocket.rs
The `max_write_buffer_size: 2048` looks like it might have been a mistake but it's definitely wrong. I'm not sure what the original intention was, but I don't think it matters for a simple example so I'm letting it take the default. Lemme know if you want something else there. 
For the undocumented new field on the welcome message, idk
=> Fix eventsub_websocket example 

Cargo.toml, src/eventsub/channel/chat/notification.rs, src/helix/client/client_ext.rs, src/helix/endpoints/eventsub/create_conduit.rs, src/helix/endpoints/eventsub/get_conduit_shards.rs, src/helix/endpoints/eventsub/update_conduit_shards.rs, src/helix/ser.rs, src/lib.rs, src/pubsub/mod.rs
This PR resolves _some_ clippy warnings. `#![cfg_attr(test, allow(deprecated))]` was added in `lib.rs` to make editing with rust-analyzer easier. Adding `#![allow(deprecated)]` for the `pubsub` module doesn't work, because of the test macros ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e1f2ca45f2ba2a07921ce982b92eb90a)).
The only remaining warnings are from `too_long_first_doc_paragraph` in top-level doc-comments (I don't know how to silence these, as `#[allow(...)]` doesn't work :/).
Other than that, `twitch_types` still has some warnings. These have been fixed, but there's no release yet (also not really needed, imo).
https://github.com/twitch-rs/twitch_api/pull/419 was partly done in https://github.com/twitch-rs/twitch_api/pull/425 (only the …
=> fix(clippy): resolve some new clippy warnings

CHANGELOG.md, src/helix/endpoints/moderation/get_automod_settings.rs, src/helix/endpoints/moderation/mod.rs, src/helix/endpoints/moderation/update_automod_settings.rs, src/helix/mod.rs, src/helix/request.rs, src/helix/request/errors.rs
Adds
- [`Get AutoMod Settings`](https://dev.twitch.tv/docs/api/reference/#get-automod-settings)
- [`Update AutoMod Settings`](https://dev.twitch.tv/docs/api/reference/#update-automod-settings)
They don't have a helper yet. Imo, we should organize the helpers a bit - `client_ext.rs` is quite big - maybe we can add some [`// MARK: <category>`](https://code.visualstudio.com/docs/getstarted/userinterface#_minimap) (?).
To make parsing responses with a single entry in `data` a bit easier, I've added `parse_single_return`.
=> feat: add Get/Update AutoMod Settings endpoints

Cargo.lock, src/client.rs, src/helix/client/client_ext.rs, src/helix/endpoints/channels/snooze_next_ad.rs, src/helix/endpoints/chat/send_chat_announcement.rs, src/helix/endpoints/chat/send_chat_message.rs, src/helix/endpoints/eventsub/create_eventsub_subscription.rs, src/helix/endpoints/moderation/add_blocked_term.rs, src/helix/endpoints/moderation/update_shield_mode_status.rs, xtask/Cargo.toml
- Fewer explicit lifetimes
- ~~Simplified boolean expression~~ `Option::is_none_or` requires nightly
- Update to `rustdoc-types` 0.32 (changes the ID type from string to int)
- [`too_long_first_doc_paragraph`](https://redirect.github.com/rust-lang/rust-clippy/issues/13315) warnings remain
=> Address new warnings and update`rustdoc-types`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/helix/client/client_ext.rs, src/helix/endpoints/moderation/get_unban_requests.rs, src/helix/endpoints/moderation/mod.rs, src/helix/endpoints/moderation/resolve_unban_request.rs, src/helix/mod.rs, xtask/src/collect_endpoints/helix.rs
Adds
- [Get Unban Requests](https://dev.twitch.tv/docs/api/reference/#get-unban-requests)
- [Resolve Unban Requests](https://dev.twitch.tv/docs/api/reference/#resolve-unban-requests) (renamed to `resolve_unban_request` since only one can be resolved at a time)
Updates `twitch_types` to 0.4.6.
=> feat: add `Get/Resolve Unban Requests` endpoints

src/helix/client/client_ext.rs, src/helix/endpoints/moderation/get_moderated_channels.rs, src/helix/endpoints/moderation/mod.rs, src/helix/mod.rs
Adds [`Get Moderated Channels`](https://dev.twitch.tv/docs/api/reference#get-moderated-channels). Now we support all moderation endpoints.
=> feat: add `Get Moderated Channels`

Cargo.toml, src/helix/client/client_ext.rs, src/helix/endpoints/chat/get_shared_chat_session.rs, src/helix/endpoints/chat/mod.rs, src/helix/mod.rs, src/helix/request.rs
Adds [`Get Shared Chat Session`](https://dev.twitch.tv/docs/api/reference#get-shared-chat-session). I added a `ZeroOrOne` helper to deserialize an array that must contain zero or one item to a `Option<T>` (without going through a `Vec<T>` in the middle).
=> feat: add `Get Shared Chat Session`

src/eventsub/automod/message/hold.rs, src/eventsub/automod/message/mod.rs, src/eventsub/automod/message/update.rs, src/eventsub/automod/mod.rs, src/eventsub/automod/settings/mod.rs, src/eventsub/automod/settings/update.rs, src/eventsub/automod/terms/mod.rs, src/eventsub/automod/terms/update.rs, src/eventsub/event.rs, src/eventsub/mod.rs
Adds 
- [`automod.message.hold`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodmessagehold)
- [`automod.message.update`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodmessageupdate)
- [`automod.settings.update`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodsettingsupdate)
- [`automod.terms.update`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodtermsupdate)
=> feat: add `automod.*` EventSub topics

src/helix/client/client_ext.rs, src/helix/endpoints/users/mod.rs, src/helix/endpoints/users/update_user.rs, src/helix/mod.rs, xtask/src/collect_endpoints/helix.rs
Adds [`Update User`](https://dev.twitch.tv/docs/api/reference/#update-user) (last non-extension endpoint for users).
=> feat: add `Update User`

Cargo.lock, Cargo.toml, src/helix/client/client_ext.rs, src/helix/endpoints/streams/create_stream_marker.rs, src/helix/endpoints/streams/get_stream_key.rs, src/helix/endpoints/streams/get_stream_markers.rs, src/helix/endpoints/streams/mod.rs, src/helix/mod.rs
Adds
- [`Get Stream Key`](https://dev.twitch.tv/docs/api/reference/#get-stream-key)
- [`Create Stream Marker`](https://dev.twitch.tv/docs/api/reference/#create-stream-marker)
- [`Get Stream Markers`](https://dev.twitch.tv/docs/api/reference/#get-stream-markers)
The markers returned by the endpoints are different (according to the docs). `Get Stream Markers` returns a marker with a `url`, but `Create Stream Marker` doesn't include that URL.
=> feat: add remaining `Streams` Helix endpoints

Cargo.lock, Cargo.toml, deny.toml, src/eventsub/automod/message/hold.rs, src/eventsub/automod/message/mod.rs, src/eventsub/automod/message/update.rs, src/eventsub/automod/mod.rs, src/eventsub/channel/chat/mod.rs, src/eventsub/channel/chat/user_message_hold.rs, src/eventsub/channel/chat/user_message_update.rs, src/eventsub/channel/mod.rs, src/eventsub/event.rs, src/eventsub/mod.rs
...and I noticed the message definitions between `automod.message` and `channel.chat.message` are different 🙃.
Adds
- `channel.chat.user_message_hold`
- `channel.chat.user_message_update`
- `automod.message.hold` (the new beta for v2)
- `automod.message.update` (the new beta for v2)
=> feat(eventsub): add more automod related events

Cargo.lock, Cargo.toml, src/eventsub/automod/message/hold.rs, src/eventsub/automod/message/update.rs, src/eventsub/automod/mod.rs, src/eventsub/channel/channel_points_custom_reward/remove.rs, src/eventsub/channel/chat/message.rs, src/eventsub/channel/subscription/end.rs, src/eventsub/channel/subscription/gift.rs, src/eventsub/channel/subscription/message.rs, src/eventsub/mod.rs, xtask/src/collect_endpoints/eventsub.rs
- Adds the version to the documentation (some endpoints have v1 and v2/beta)
- Fixes #451
- Fixes https://github.com/twitch-rs/twitch_api/issues/450
=> EventSub housekeeping

src/eventsub/channel/channel_points_automatic_reward_redemption/add.rs, src/eventsub/channel/channel_points_automatic_reward_redemption/mod.rs, src/eventsub/channel/mod.rs, src/eventsub/event.rs, src/eventsub/mod.rs
Adds [`channel.channel_points_automatic_reward_redemption.add`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchannel_points_automatic_reward_redemptionadd).
=> feat: add channel.channel_points_automatic_reward_redemption.add

src/helix/client/client_ext.rs, src/helix/endpoints/games/get_games.rs
Two warnings that pop up when generating the docs.
=> Fix warnings when generating documentation

src/eventsub/mod.rs, src/helix/client/client_ext.rs, src/helix/endpoints/eventsub/create_conduit.rs, src/helix/endpoints/eventsub/delete_conduit.rs, src/helix/endpoints/eventsub/get_conduit_shards.rs, src/helix/endpoints/eventsub/get_conduits.rs, src/helix/endpoints/eventsub/mod.rs, src/helix/endpoints/eventsub/update_conduit.rs, src/helix/endpoints/eventsub/update_conduit_shards.rs, src/helix/mod.rs, xtask/src/collect_endpoints/helix.rs
Adds the two remaining conduit endpoints and migrates the existing ones to use types from `twitch_types`.
=> Complete Conduits and use `twitch_types`

src/eventsub/automod/message/hold.rs, src/eventsub/automod/message/mod.rs, src/eventsub/automod/message/update.rs, src/eventsub/automod/mod.rs, src/eventsub/event.rs, src/eventsub/mod.rs
In https://github.com/twitch-rs/twitch_api/commit/83208f0df7dc729636c8411968f11b74feba15ee I missed `eventsub::enum_field_as_inner` - this makes the `AutomodHeldReason` a bit nicer to use.
=> fix(eventsub): flatten automod v2 held reason

Cargo.lock, Cargo.toml, deny.toml
`url` 2.5.2 pulled in `idna < 1.0` which has [`RUSTSEC-2024-0421`](https://rustsec.org/advisories/RUSTSEC-2024-0421). 2.5.4 updated to `idna 1.x`.
=> deps: update `url`

Cargo.toml, src/helix/client/client_ext.rs, src/helix/endpoints/users/get_user_active_extensions.rs, src/helix/endpoints/users/get_user_extensions.rs, src/helix/endpoints/users/mod.rs, src/helix/endpoints/users/update_user_extensions.rs, src/helix/mod.rs
This adds
- ~~[Get Channel iCalendar](https://dev.twitch.tv/docs/api/reference#get-channel-icalendar)~~ → https://github.com/twitch-rs/twitch_api/pull/463
- [Get User Extensions](https://dev.twitch.tv/docs/api/reference#get-user-extensions)
- [Get User Active Extensions](https://dev.twitch.tv/docs/api/reference#get-user-active-extensions)
- [Update User Extensions](https://dev.twitch.tv/docs/api/reference#update-user-extensions)
These are the only extension endpoints that we can implement, as they're for the current broadcaster. I don't think we should implement the GuestStar endpoints yet, since the docs aren't updated to reflect the latest changes (many things are wrong there rn).
I don't think there's any other endpoint we _have_ to implement.
=> feat(helix): Implement remaining Schedule and User endpoints

src/helix/client/client_ext.rs, src/helix/endpoints/ccls/get_content_classification_labels.rs, src/helix/endpoints/ccls/mod.rs, src/helix/endpoints/mod.rs, src/helix/mod.rs, xtask/src/collect_endpoints/helix.rs
Adds [`Get Content Classification Labels`](https://dev.twitch.tv/docs/api/reference/#get-content-classification-labels).
=> feat: add `Get Content Classification Labels`

Cargo.lock, Cargo.toml, src/eventsub/channel/chat_settings/mod.rs, src/eventsub/channel/chat_settings/update.rs, src/eventsub/channel/guest_star_guest/mod.rs, src/eventsub/channel/guest_star_guest/update.rs, src/eventsub/channel/guest_star_session/begin.rs, src/eventsub/channel/guest_star_session/end.rs, src/eventsub/channel/guest_star_session/mod.rs, src/eventsub/channel/guest_star_settings/mod.rs, src/eventsub/channel/guest_star_settings/update.rs, src/eventsub/channel/mod.rs, src/eventsub/channel/moderate.rs, src/eventsub/channel/moderator/add.rs, src/eventsub/channel/moderator/mod.rs, src/eventsub/channel/moderator/remove.rs, src/eventsub/channel/suspicious_user/message.rs, src/eventsub/channel/suspicious_user/mod.rs, src/eventsub/channel/suspicious_user/update.rs, src/eventsub/channel/unban_request/create.rs, src/eventsub/channel/unban_request/mod.rs, src/eventsub/channel/unban_request/resolve.rs, src/eventsub/channel/vip/add.rs, src/eventsub/channel/vip/mod.rs, src/eventsub/channel/vip/remove.rs, src/eventsub/channel/warning/acknowledge.rs, src/eventsub/channel/warning/mod.rs, src/eventsub/channel/warning/send.rs, src/eventsub/event.rs, src/eventsub/mod.rs
Finally, all `channel` topics... I hope there aren't many typos and copy-paste errors.
There's one typo in `twitch-oauth2` I noticed, though 😔
=> feat(eventsub): add remaining `channel.*` topics

Cargo.lock, Cargo.toml, src/eventsub/event.rs, src/eventsub/mod.rs, src/eventsub/user/mod.rs, src/eventsub/user/whisper/message.rs, src/eventsub/user/whisper/mod.rs
[`user.whisper.message`](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#userwhispermessage) - This is the last remaining event. The example for the payload in the docs is missing the `cost` in the subscription.
=> feat: add `user.whisper.message`

CHANGELOG.md, Cargo.lock, src/eventsub/channel/bits/mod.rs, src/eventsub/channel/bits/use.rs, src/eventsub/channel/mod.rs, src/eventsub/event.rs, src/eventsub/mod.rs
Implementation of [channel.bits.use](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelbitsuse).
The example for the payload in the docs is missing the `power_up` in the event.
=> feat: add `channel.bits.use`

CHANGELOG.md, src/helix/client/client_ext.rs
I was wondering why `get_eventsub_subscriptions` only returned 100 items. Turns out, `make_stream` was only requesting the first chunk.
After requesting, a deque is created from the items and the first item is returned:
```rust
let mut deq = fun(resp.data.clone());
deq.pop_front().map(|d| (Ok(d), state.process(resp, deq)))
```
`state.process` transitions into `State::Cont` which yields all the remaining values. For `get_eventsub_subscriptions` however, there's only one value in the deque, which was removed by `pop_front`. If the deque is empty when subsequently handling `Cont`, the stream stops (`None` is returned).
I changed `State::process` to immediately transition to `Next` if the queue was empty. This adds the invariant that `State::Cont` will always hold a non-empty deque.
--- …
=> fix(client): transition to `Cont` when receiving single cunks

src/helix/endpoints/clips/create_clip.rs
Updates the create-clip API to use the POST method instead of GET along with some minor docs updates 
- Updates the create-clip request to use the POST method
- Align the documentation with the latest current Twitch documentation
- Closes #496
=> fix: create clip api method and change response type
