twitch-rs/twitch_api

Cargo.lock
twitchapi/Cargo.toml
twitchapi/README.md
twitchapi/src/helix/mod.rs
twitchapi/src/lib.rs

release twitch_api2 0.4.1

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/gh-pages.yml
.gitmodules
Cargo.lock
Cargo.toml
README.md
src/lib.rs

this tries to not do the sins in  #14

add twitch_oauth2 as a submodule

---

.github/workflows/ci.yml

bump and run tests on master

---

Cargo.toml
examples/create_follower.rs
examples/remove_followers.rs
src/client.rs
src/helix/mod.rs
src/helix/users.rs

fix docs, and add more follower endpoints

---

Cargo.lock
Cargo.toml

in preparation for new release. Want to get pubsub in also first however

bump twitch_oauth2

---

.github/bors.toml
.github/workflows/audit.yml
.github/workflows/ci.yml
deny.toml

Deny check and bors

---

src/helix/bits.rs
src/helix/mod.rs
src/helix/search.rs

adds bits endpoints

---

src/pubsub/hype_train.rs

`use_personalized_settings` may always be returned. Will have to see in the future

add use_personalized_settings

---

.github/workflows/ci.yml
Cargo.lock
src/helix/mod.rs
src/helix/ser.rs
src/pubsub/channel_bits.rs
src/pubsub/channel_bits_badge.rs
src/pubsub/channel_cheer.rs
src/pubsub/channel_points.rs
src/pubsub/channel_sub_gifts.rs
src/pubsub/channel_subscriptions.rs
src/pubsub/community_points.rs
src/pubsub/following.rs
src/pubsub/hype_train.rs
src/pubsub/moderation.rs
src/pubsub/raid.rs
src/pubsub/video_playback.rs
src/tmi/mod.rs

this fixes RUSTSEC-2020-0071 and some issues with formatting

bump deps and run rustfmt

---

src/pubsub/channel_points.rs
src/pubsub/moderation.rs

fixes unban requests, update-redemption-statuses-finished and a typo in channel points
bors r+

Small fixes

---

Cargo.lock
Cargo.toml
src/eventsub/channel.rs
src/eventsub/channel/cheer.rs
src/eventsub/channel/follow.rs
src/eventsub/channel/hypetrain.rs
src/eventsub/channel/subscribe.rs
src/eventsub/mod.rs
src/eventsub/user.rs
src/helix/bits.rs
src/helix/channels.rs
src/helix/clips.rs
src/helix/eventsub.rs
src/helix/games.rs
src/helix/hypetrain.rs
src/helix/mod.rs
src/helix/moderation.rs
src/helix/points.rs
src/helix/search.rs
src/helix/streams.rs
src/helix/subscriptions.rs
src/helix/tags.rs
src/helix/users.rs
src/helix/videos.rs
src/helix/webhooks.rs
src/pubsub/following.rs
src/pubsub/hypetrain.rs
src/pubsub/mod.rs
src/pubsub/moderation.rs
src/pubsub/raid.rs

release v0.5.0-alpha.3

---

src/helix/subscriptions/get_broadcaster_subscriptions.rs

add user_login and broadcaster_login to `BroadcasterSubscription`

---

src/helix/mod.rs
src/lib.rs
src/pubsub/mod.rs

bump twitch_oauth2 and fix lint error

---

src/helix/mod.rs
src/lib.rs
src/pubsub/mod.rs

doesn't add anything for this usecase

remove doc_spotlight (now renamed to doc_notable_trait)

---

src/eventsub/mod.rs
src/helix/bits/get_bits_leaderboard.rs
src/helix/channels/get_channel_information.rs
src/helix/eventsub.rs
src/helix/eventsub/create_eventsub_subscription.rs
src/helix/eventsub/get_eventsub_subscriptions.rs
src/helix/mod.rs
src/helix/search/search_categories.rs
src/helix/subscriptions/check_user_subscription.rs
src/helix/users.rs
src/helix/users/create_user_follows.rs
src/helix/users/get_users_follows.rs
src/helix/webhooks/get_webhook_subscriptions.rs

- make parsing of a seemingly correct payload more accessible for custom parsing
- fix parsing of total in Get User Follows and Get Webhook Subscriptions
- add missing fields related to cost to eventsub subscriptions
resolves #95

better deser for responses

---

examples/modify_channel.rs
src/eventsub/channel/channel_points_custom_reward/remove.rs
src/eventsub/channel/channel_points_custom_reward/update.rs
src/eventsub/channel/channel_points_custom_reward_redemption/add.rs
src/eventsub/channel/channel_points_custom_reward_redemption/update.rs
src/eventsub/channel/raid.rs
src/helix/channels/modify_channel_information.rs
src/helix/clips/get_clips.rs
src/helix/games/get_top_games.rs
src/helix/mod.rs
src/helix/search/search_channels.rs
src/helix/streams/get_streams.rs
src/helix/teams/get_teams.rs
src/helix/users/create_user_follows.rs
src/helix/videos/get_videos.rs
src/helix/webhooks/topics/streams/stream_changed.rs
src/pubsub/channel_points.rs
src/pubsub/hypetrain.rs
src/types.rs

- fix some pubsub stuff
- update Get Videos, add stream_id and muted_segments
- add game_name to Search Channels
- add duration to Get Clips
- add is_mature to Get Streams
- remove strip_option from all builders

some additions and changes

---

Cargo.lock
Cargo.toml

- make docs build on docs.rs
- release twitch_api2 0.5.0-beta.2
bors r+
🤖

release v0.5.0 beta.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/lib.rs

[v0.5.0] - 2021-05-08
[Commits](https://github.com/Emilgardis/twitch_api2/compare/v0.4.1...v0.5.0)
* Made crate runtime agnostic with custom clients using feature `client`.
* Added `unsupported` feature to enable experimental/undocumented APIs/endpoints/topics.
* Made most fields deny unknown fields by enabling feature `deny_unknown_fields`.
* Added `all` feature to enable all feature sans `unsupported` and `deny_unknown_fields`.
* Added most PubSub topics.
- channel-bits-badge-unlocks
- channel-bits-events-v2
- channel-cheer-events-public-v1
- channel-points-channel-v1
- channel-sub-gifts-v1
- channel-subscribe-events-v1
- chat_moderator_actions
- community-points-channel-v1
- following
- hype-train-events-v1
- hype-train-events-v1.rewards
- raid
- video-playback
- video-playback-by-id
* …

release v0.5.0

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/eventsub/mod.rs
src/helix/bits/get_bits_leaderboard.rs
src/helix/channels/get_channel_information.rs
src/helix/eventsub/create_eventsub_subscription.rs
src/helix/eventsub/get_eventsub_subscriptions.rs
src/helix/mod.rs
src/helix/points/create_custom_rewards.rs
src/helix/points/update_custom_reward.rs
src/helix/points/update_redemption_status.rs
src/helix/search/search_categories.rs
src/helix/subscriptions/check_user_subscription.rs
src/helix/users/create_user_follows.rs
src/helix/users/get_users_follows.rs
src/helix/webhooks/get_webhook_subscriptions.rs
src/helix/webhooks/hub.rs
src/lib.rs
src/pubsub/mod.rs
src/tmi/mod.rs

Adds serde_ignored to log ignored fields using `tracing::warn`
resolves #135

add serde_ignored to warn on ignored fields

---

CHANGELOG.md
src/pubsub/moderation.rs

Reverts Emilgardis/twitch_api2#141
this seems to have been the correct thing to do.

Revert "correct /vip pubsub"

---

src/eventsub/channel.rs
src/eventsub/channel/poll.rs
src/eventsub/channel/poll/begin.rs
src/eventsub/channel/poll/end.rs
src/eventsub/channel/poll/progress.rs
src/eventsub/channel/prediction.rs
src/eventsub/channel/prediction/begin.rs
src/eventsub/channel/prediction/end.rs
src/eventsub/channel/prediction/lock.rs
src/eventsub/channel/prediction/progress.rs
src/eventsub/mod.rs
src/helix/mod.rs
src/helix/points/update_custom_reward.rs
src/helix/polls.rs
src/helix/polls/create_poll.rs
src/helix/polls/end_poll.rs
src/helix/polls/get_polls.rs
src/helix/predictions.rs
src/helix/predictions/create_prediction.rs
src/helix/predictions/end_prediction.rs
src/helix/predictions/get_predictions.rs
src/lib.rs
src/types.rs

adds the new polls and prediction helix and eventsub endpoints

polls and predictions

---

CHANGELOG.md
Cargo.toml
examples/followed_streams.rs
examples/get_moderation.rs
src/helix/client_ext.rs
src/helix/mod.rs

The types on this thing is pretty wild, there's probably some unnecessary bounds here and there. But this works
fixes #149

implement streamed responses

---

CHANGELOG.md
src/eventsub/channel/mod.rs
src/eventsub/channel/subscription/end.rs
src/eventsub/channel/subscription/gift.rs
src/eventsub/channel/subscription/message.rs
src/eventsub/channel/subscription/mod.rs
src/eventsub/mod.rs
src/types.rs

- fix docs for end subscription
- add eventsub subscription gift
- add eventsub resubscription message
add some missing eventsub topics that were recently promoted

subscription eventsub

---

src/lib.rs

hide readme doctest and fix typo

---

.github/workflows/codecov.yml.x

disable code cov

---

src/helix/streams/get_streams.rs

allow null tag_ids

---

src/pubsub/automod_queue.rs
src/pubsub/hypetrain.rs
src/types.rs

- add new fields creator_color and participations to pubsub hyperaid
- add new automod variant
- fix types::User not being deny_unknown_fields
bors r+

pubsub fixes

---

CHANGELOG.md
src/eventsub/mod.rs

make `parse_http` and `verify` on `Payload` generic on body type

---

.github/workflows/ci.yml
.github/workflows/gh-pages.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
src/lib.rs

some bumps, update msrv
resolves #203

bumps and bumps, msrv updated

---

src/types.rs

fix wrong template checking

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/gh-pages.yml

some ci changes

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
src/lib.rs

- bump twitch_oauth2
- release twitch_api2 0.6.0-rc.3

release v0.6.0 rc.3

---

src/pubsub/automod_queue.rs
src/pubsub/hypetrain.rs
src/pubsub/moderation.rs

- add field to hypetrain for approaching hypetrain id
- add new params to pubsub
bors r+

sync pubsub

---

src/pubsub/moderation.rs

adds /unraid to pubsub
Fixes #239

add unraid command

---

src/helix/streams/get_streams.rs

change type of game_name to a string

---

src/eventsub/event.rs
src/eventsub/mod.rs

- make make_stream future send
- make eventsub parsing from text actually work

no empty struct

---

.github/workflows/gh-pages.yml
docs/pre-content.html

remove precontent in gh-pages

---

src/helix/client/client_ext.rs
src/helix/endpoints/moderation/ban_user.rs
src/helix/endpoints/moderation/unban_user.rs

also adds client method for banning and unbanning

fix wrong ban

---

CHANGELOG.md
src/helix/client/client_ext.rs
src/helix/endpoints/channels/mod.rs
src/helix/endpoints/chat/mod.rs
src/helix/endpoints/chat/send_chat_announcement.rs
src/helix/endpoints/moderation/remove_channel_moderator.rs
src/helix/endpoints/whispers/mod.rs
src/helix/endpoints/whispers/send_whisper.rs
src/helix/request/errors.rs

also fixes some trailing issues

add missing ext methods

---

src/helix/endpoints/channels/get_vips.rs
src/helix/endpoints/chat/get_chatters.rs
src/helix/endpoints/clips/get_clips.rs
src/helix/endpoints/eventsub/get_eventsub_subscriptions.rs
src/helix/endpoints/games/get_top_games.rs
src/helix/endpoints/moderation/get_banned_users.rs
src/helix/endpoints/moderation/get_blocked_terms.rs
src/helix/endpoints/moderation/get_moderators.rs
src/helix/endpoints/points/get_custom_reward_redemption.rs
src/helix/endpoints/polls/get_polls.rs
src/helix/endpoints/predictions/get_predictions.rs
src/helix/endpoints/schedule/get_channel_stream_schedule.rs
src/helix/endpoints/search/search_categories.rs
src/helix/endpoints/search/search_channels.rs
src/helix/endpoints/streams/get_followed_streams.rs
src/helix/endpoints/streams/get_streams.rs
src/helix/endpoints/subscriptions/get_broadcaster_subscriptions.rs
src/helix/endpoints/subscriptions/get_broadcaster_subscriptions_events.rs
src/helix/endpoints/tags/get_all_stream_tags.rs
src/helix/endpoints/users/get_user_block_list.rs
src/helix/endpoints/users/get_users_follows.rs
src/helix/endpoints/videos/get_videos.rs
src/helix/endpoints/whispers/send_whisper.rs

add missing borrows

---

Cargo.lock
Cargo.toml
src/helix/endpoints/games/get_games.rs
src/helix/endpoints/games/get_top_games.rs
src/helix/mod.rs
src/pubsub/mod.rs

Get Games and Get Top Games IGDB Field

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/eventsub_websocket/src/util.rs
examples/mock_api.rs
examples/twitch_oauth2-integration/Cargo.toml
examples/twitch_oauth2-integration/src/lib.rs
src/client.rs
src/client/reqwest_impl.rs
src/client/surf_impl.rs
src/client/ureq_impl.rs
src/helix/client.rs
src/helix/client/client_ext.rs
src/helix/client/custom.rs
src/helix/response.rs
src/lib.rs
src/tmi/mod.rs

fix lifetimes issues

---

Cargo.lock
Cargo.toml
README.md
examples/eventsub/Cargo.toml
examples/eventsub_websocket/Cargo.toml
examples/twitch_oauth2-integration/Cargo.toml
src/helix/client/client_ext.rs
src/helix/endpoints/schedule/update_channel_stream_schedule.rs
src/lib.rs

fix send bounds

---

CHANGELOG.md
src/helix/endpoints/teams/get_channel_teams.rs

Resolves #325
related: twitchdev/issues#495

handle teams/channel returning null data

---

Cargo.lock
Cargo.toml
README.md
src/lib.rs

this should be the last rc release

release twitch_api 0.7.0-rc.5

---

Cargo.lock
Cargo.toml
README.md
src/lib.rs
xtask/src/main.rs

Fixes the issue identified in #363

ensure publish would work

---

src/eventsub/mod.rs

I think this resolves #217 now

explain eventsub

---

src/eventsub/channel/hypetrain/mod.rs

this should've been done in #305

add missing contribution type

---

Cargo.lock
Cargo.toml
README.md
release.toml
src/lib.rs

- bump deps and fix release.toml
- release twitch_api 0.7.0-rc.7

release 0.7.0 rc.7

---

src/eventsub/mod.rs

Add missing twitch enventsub status

---

CHANGELOG.md
src/helix/endpoints/chat/get_channel_chat_badges.rs
src/helix/endpoints/chat/get_global_chat_badges.rs
src/helix/endpoints/chat/mod.rs

https://dev.twitch.tv/docs/api/reference/#get-channel-chat-badges
https://dev.twitch.tv/docs/api/reference/#get-global-chat-badges
Added title and description to the chat badges. I needed it for one of my projects, so I figured I may as well contribute back.

feat: Add title and description to chat badges

---

src/helix/endpoints/channels/get_followed_channels.rs

fixed this [issue](https://github.com/twitch-rs/twitch_api/issues/437)

fix: wrong followed_at type

---

.github/workflows/codecov.yml

The only change from https://github.com/twitch-rs/twitch_api/pull/416 that didn't make it in yet (except for dependabot).

ci: enable codecov

---

Cargo.toml
src/eventsub/channel/mod.rs
src/eventsub/channel/shared_chat/begin.rs
src/eventsub/channel/shared_chat/end.rs
src/eventsub/channel/shared_chat/mod.rs
src/eventsub/channel/shared_chat/update.rs
src/eventsub/event.rs
src/eventsub/mod.rs

Adds the `begin`, `end`, and `update` events for `channel.shared_chat`.

feat: `channel.shared_chat.*`

---

src/eventsub/channel/mod.rs

fix: correct re-exports to be inline

---

src/eventsub/channel/chat/message.rs
src/eventsub/channel/chat/message_delete.rs
src/eventsub/channel/chat/notification.rs
src/eventsub/mod.rs

add shared chat session info to channel.chat.*

---

.github/workflows/sync.yml
Cargo.lock
src/eventsub/mod.rs

- add autoupdater for docs
- bump openssl

auto sync docs

---

CHANGELOG.md
src/eventsub/channel/suspicious_user/message.rs

fix nullable fields in channel.suspicious_user.message

---

src/eventsub/channel/suspicious_user/message.rs

actually fix nullable field

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/helix/client/client_ext.rs
src/helix/endpoints/users/mod.rs
src/helix/mod.rs
src/lib.rs

Adds a helper for making it easier to get multiple users by their logins.
Resolves #486

add `HelixClient::get_users_from_logins`

---

CHANGELOG.md
Cargo.lock
src/eventsub/mod.rs

add `conduit_deleted` to `eventsub::Status`
